language: c

compiler:
    - gcc

os:
    -linux
    
before_install:
  - pip install --user cpp-coveralls
    
script:
    - make -C engine/ clean
    - make -C tests/ clean  
    - make -C tests/cu
    - make -C tests/
    - tests/jupitests  

after_success:
  - coveralls -b engine -e engine/main.c -i engine -i engine/pieces --gcov-options '\-lp *.c' 
