language: c

compiler:
    - gcc

os:
    -linux
    
before_install:
  - pip install --user cpp-coveralls
    
script:
    - make -C engine/ clean
    - make -C tests/ clean  
    - make -C tests/cu
    - make -C tests/
    - tests/jupitests  
    - gcov engine/*.c engine/pieces/*.c  

after_success:
    -  bash <(curl -s https://codecov.io/bash)
    #  - coveralls -b engine -r engine -e engine/main.c -i engine --gcov-options '\-l *.c' 
